# Header Info
#

---
- hosts: all
  tasks:
    - name: Ping hosts
      ping:

- hosts: suse_ai
  vars:
    suse_ai_rancher_hostname: rancher.example.com
    suse_ai_rancher_bootstrap_password: admin
  roles:
    - suse-ai
