global:
  imagePullSecrets:
    - application-collection
ingress:
  enabled: false
defaultModel: "gemma:2b"
ollama:
  models:
    pull:
      - "gemma:2b"
      - "llama3.1"
    run:
      - "gemma:2b"
      - "llama3.1"
  gpu:
    enabled: true
    type: "nvidia"
    number: 1
persistentVolume:
  enabled: true
  storageClass: longhorn
