global:
  imagePullSecrets:
    - application-collection

ollamaUrls:
  - http://open-webui-ollama.suseai.svc.cluster.local:11434

persistence:
  enabled: true
  storageClass: longhorn-xfs

ollama:
  enabled: true
  ingress:
    enabled: false
  defaultModel: "gemma:2b"
  ollama:
    models:
      - "gemma:2b"
      - "llama3.1"
    gpu:
      enabled: true
      type: "nvidia"
      number: 1
    persistentVolume:
      enabled: true
      storageClass: longhorn-xfs

pipelines:
  enabled: false
  persistence:
    storageClass: longhorn-xfs

ingress:
  enabled: true
  class: ""
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: suse-ollama-webui
  tls: true

extraEnvVars:
  - name: DEFAULT_MODELS
    value: "gemma:2b"
  - name: DEFAULT_USER_ROLE
    value: "user"
  - name: WEBUI_NAME
    value: "SUSE AI"
  - name: GLOBAL_LOG_LEVEL
    value: "INFO"
  - name: RAG_EMBEDDING_MODEL
    value: "sentence-transformers/all-MiniLM-L6-v2"
  - name: VECTOR_DB
    value: "milvus"
  - name: MILVUS_URI
    value: http://milvus.suseai.svc.cluster.local:19530
  - name: INSTALL_NLTK_DATASETS
    value: "true"
