# Install Rancher
- block:
    - name: Ensure kube directory exists
      file:
        path: ~/.kube
        state: directory

    - name: Set kubeconfig for user
      copy:
        src: /etc/rancher/rke2/rke2.yaml
        dest: "{{ ansible_facts.user_dir }}/.kube/config"
        owner: "{{ ansible_user_uid }}"
        group: "{{ ansible_user_gid }}"
        remote_src: true
      become: true
      when: suse_ai_install_rke2

    - name: Add Rancher Prime helm repo
      kubernetes.core.helm_repository:
        name: rancher-prime
        repo_url: "https://charts.rancher.com/server-charts/prime"

    - name: Add Jetstack helm repo
      kubernetes.core.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Install cert-manager
      kubernetes.core.helm:
        name: cert-manager
        chart_ref: jetstack/cert-manager
        release_namespace: cert-manager
        create_namespace: true
        set_values:
          - value: crds.enabled=true

    - name: Install rancher-prime
      kubernetes.core.helm:
        name: rancher
        chart_ref: rancher-prime/rancher
        release_namespace: cattle-system
        create_namespace: true
        set_values:
          - value: "hostname={{ suse_ai_rancher_hostname }}"
          - value: rancherImage='registry.rancher.com/rancher/rancher'
          - value: replicas=-1
          - value: "bootstrapPassword={{ suse_ai_rancher_bootstrap_password }}"

  when:
    - suse_ai_install_rancher | default(true)
    - inventory_hostname in primary_control_nodes
